<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- Este es el DTD de los Argumentos de los mensajes entre los agentes -->
<!DOCTYPE Dialogo [ 
    <!ELEMENT Dialogo (Mensaje)*>
        <!ELEMENT Mensaje (Agente_Origen, Agente_Destino, Argumento*)>
            <!ELEMENT Agente_Origen (#PCDATA)>
            <!ELEMENT Agente_Destino (#PCDATA)>
              <!ATTLIST Agente_Destino broadcast (si | no) #REQUIRED>
              
            <!ELEMENT Argumento (Conclusion, Derivacion, Estado?)>
              <!ATTLIST Argumento id CDATA #REQUIRED>
              <!ATTLIST Argumento id_ataque CDATA #IMPLIED>
                
              <!ELEMENT Conclusion (#PCDATA)>
              <!ELEMENT Derivacion (Regla*)>
                <!ELEMENT Regla (#PCDATA)>
                    <!ATTLIST Regla tipo (Default | Estricta) #REQUIRED>
                    
              <!ELEMENT Estado ( #PCDATA | Derrotado | NoDerrotado )*>
                <!ATTLIST Estado cerrado (si | no) #REQUIRED>
]>

<!--

    Pi      = { [bird <- chicken], [chicken], [scared] }
    
    Delta   = { [flies -< bird], [~flies -< chicken], [flies -< chicken, scared], [nest_in_trees -< flies] }
    
    Simbologia:
               Simbolo æ en la regla A æ B:
                    A partir de "B" se concluye que "A";
               Simbolo -< reemplazado por -#;
               Simbolo <- reemplazado por #-;

-->
<Dialogo>
    <Mensaje>
        <Agente_Origen>Agente_1</Agente_Origen>
        <Agente_Destino broadcast="si">  </Agente_Destino>
        <Argumento id="1">
            <Conclusion> flies æ chicken </Conclusion>
            <Derivacion>
                <Regla tipo="Estricta"> chicken </Regla>
                <Regla tipo="Estricta"> bird #- chicken </Regla>
                <Regla tipo="Default"> flies -# bird </Regla>
            </Derivacion>
            <Estado cerrado="no">
                NoDerrotado
            </Estado>
        </Argumento>
    </Mensaje>
    
    <Mensaje>
        <Agente_Origen>Agente_2</Agente_Origen>
        <Agente_Destino broadcast="si">Agente_1</Agente_Destino>
        <Argumento id="2" id_ataque="1">
            <Conclusion> ~flies æ chicken </Conclusion>
            <Derivacion>
                <Regla tipo="Estricta"> chicken </Regla>
                <Regla tipo="Default"> ~flies #- chicken </Regla>
            </Derivacion>
            <Estado cerrado="no">
                NoDerrotado
            </Estado>
        </Argumento>
    </Mensaje>
    
    <Mensaje>
        <Agente_Origen>Agente_3</Agente_Origen>
        <Agente_Destino broadcast="si">Agente_2</Agente_Destino>
        <Argumento id="3" id_ataque="2">
            <Conclusion> flies æ chicken, scared </Conclusion>
            <Derivacion>
                <Regla tipo="Estricta"> chicken </Regla>
                <Regla tipo="Estricta"> scared </Regla>
                <Regla tipo="Default"> flies -# chicken, scared </Regla>
            </Derivacion>
            <Estado cerrado="no">
                NoDerrotado
            </Estado>
        </Argumento>
    </Mensaje>
</Dialogo>